// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from decoder.djinni

#pragma once

#include <memory>
#include <string>

namespace decoder {

class Decoder {
public:
    virtual ~Decoder() {}

    /** create() is to create an instance of the decoder */
    static std::shared_ptr<Decoder> create();

    /** method for decoding */
    virtual std::string decode(int8_t* image) = 0;
};

}  // namespace decoder
